let SelectedAlgoElement = document.getElementById('select-algo');
let SeachItemElement = document.getElementById('search-item');
let SetSizeElement = document.getElementById('set-size');
let AnimStateElement = document.getElementById('anim-state');
let ErrorElement = document.getElementById('error');
let RandomizeArrayElement = document.getElementById('do-random');
let StartAnimateElement = document.getElementById('start_anim');
let VisualizationAreaElement = document.getElementById('visualization-area');
let dataSetArray = [];
let SpeedValueElement = document.getElementById('speed_value');
let speed = SpeedValueElement.innerText;
const SEARCH_TYPE = 1;
const SORT_TYPE = 2;
const PRE_WIDTH = 45;
const PRE_MARGIN = 2;
let CanvasDimensions = {width:PRE_WIDTH, marginLeft:PRE_MARGIN};
let defaultMarginTop = {searching:4,sorting:14};
window.onload = function() {
  setDataSetSize();
  initSpeedRange();
};
